#!/usr/bin/env python3
"""
Generate a complete Odoo 19 module structure following OCA guidelines.
Usage: python init_module.py <module_name> --path <output_dir>
"""

import os
import sys
import argparse
from pathlib import Path


def snake_case(name):
    """Convert module name to snake_case."""
    return name.lower().replace('-', '_').replace(' ', '_')


def create_module_structure(module_name, output_dir, author="Your Company", depends="base"):
    """Create complete Odoo module structure."""
    module_name = snake_case(module_name)
    module_path = Path(output_dir) / module_name
    
    # Create directory structure
    dirs = [
        module_path,
        module_path / "models",
        module_path / "views",
        module_path / "security",
        module_path / "data",
        module_path / "demo",
        module_path / "static" / "description",
    ]
    
    for dir_path in dirs:
        dir_path.mkdir(parents=True, exist_ok=True)
    
    # Create __manifest__.py
    manifest_content = f'''# Copyright {author}
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).

{{
    "name": "{module_name.replace('_', ' ').title()}",
    "summary": "Short description",
    "version": "19.0.1.0.0",
    "category": "Uncategorized",
    "website": "https://github.com/OCA/project-name",
    "author": "{author}, Odoo Community Association (OCA)",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "depends": [
        "{depends}",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/{module_name}_views.xml",
        "views/menu.xml",
    ],
    "demo": [
        "demo/{module_name}_demo.xml",
    ],
}}
'''
    
    with open(module_path / "__manifest__.py", "w") as f:
        f.write(manifest_content)
    
    # Create root __init__.py
    with open(module_path / "__init__.py", "w") as f:
        f.write(f"# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).\n\nfrom . import models\n")
    
    # Create models __init__.py
    with open(module_path / "models" / "__init__.py", "w") as f:
        f.write(f"# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).\n")
    
    # Create README.rst
    readme_content = f"""
{'=' * len(module_name)}
{module_name.replace('_', ' ').title()}
{'=' * len(module_name)}

.. !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   !! This file is generated by oca-gen-addon-readme !!
   !! changes will be overwritten.                   !!
   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

.. |badge1| image:: https://img.shields.io/badge/maturity-Beta-yellow.png
    :target: https://odoo-community.org/page/development-status
    :alt: Beta
.. |badge2| image:: https://img.shields.io/badge/licence-AGPL--3-blue.png
    :target: http://www.gnu.org/licenses/agpl-3.0-standalone.html
    :alt: License: AGPL-3

|badge1| |badge2|

This module extends Odoo with...

**Table of contents**

.. contents::
   :local:

Usage
=====

To use this module, you need to:

#. Go to ...

Bug Tracker
===========

Bugs are tracked on `GitHub Issues <https://github.com/OCA/project-name/issues>`_.
In case of trouble, please check there if your issue has already been reported.

Credits
=======

Authors
~~~~~~~

* {author}

Contributors
~~~~~~~~~~~~

* Your Name <your.email@example.com>

Maintainers
~~~~~~~~~~~

This module is maintained by the OCA.

.. image:: https://odoo-community.org/logo.png
   :alt: Odoo Community Association
   :target: https://odoo-community.org

OCA, or the Odoo Community Association, is a nonprofit organization whose
mission is to support the collaborative development of Odoo features and
promote its widespread use.

This module is part of the `OCA/project-name <https://github.com/OCA/project-name/tree/19.0/{module_name}>`_ project on GitHub.

You are welcome to contribute.
"""
    
    with open(module_path / "README.rst", "w") as f:
        f.write(readme_content)
    
    # Create empty security file
    with open(module_path / "security" / "ir.model.access.csv", "w") as f:
        f.write("id,name,model_id:id,group_id:id,perm_read,perm_write,perm_create,perm_unlink\n")
    
    # Create empty views files
    with open(module_path / "views" / f"{module_name}_views.xml", "w") as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n<odoo>\n\n</odoo>\n')
    
    with open(module_path / "views" / "menu.xml", "w") as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n<odoo>\n\n</odoo>\n')
    
    # Create empty demo file
    with open(module_path / "demo" / f"{module_name}_demo.xml", "w") as f:
        f.write('<?xml version="1.0" encoding="utf-8"?>\n<odoo>\n\n</odoo>\n')
    
    # Create icon placeholder
    with open(module_path / "static" / "description" / "icon.png.txt", "w") as f:
        f.write("Add your module icon here (icon.png)\n")
    
    print(f"✅ Module '{module_name}' created successfully at {module_path}")
    print("\nNext steps:")
    print(f"1. Add your models in models/")
    print(f"2. Add your views in views/")
    print(f"3. Configure security in security/ir.model.access.csv")
    
    return str(module_path)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate Odoo 19 module structure (OCA compliant)")
    parser.add_argument("module_name", help="Name of the module to create")
    parser.add_argument("--path", default=".", help="Output directory (default: current directory)")
    parser.add_argument("--author", default="Your Company", help="Author name")
    parser.add_argument("--depends", default="base", help="Main dependency module")
    
    args = parser.parse_args()
    
    create_module_structure(args.module_name, args.path, args.author, args.depends)
