/**
 * Lucide React Icons - Reusable Icon Components
 *
 * Menggunakan lucide-react untuk semua icon di aplikasi
 * Document: https://lucide.dev/icons/
 */

import {
    Calendar,
    MapPin,
    Mail,
    Globe,
    Phone,
    Eye,
    Clock,
    User,
    Users,
    Book,
    GraduationCap,
    Award,
    Star,
    Check,
    X,
    ChevronRight,
    ChevronLeft,
    Menu,
    Search,
    Bell,
    Settings,
    LogOut,
    Home,
    FileText,
    Image,
    Video,
    Play,
    Pause,
    Heart,
    Share2,
    MessageCircle,
    ThumbsUp,
    Send,
    Download,
    Upload,
    ExternalLink,
    Link as LinkIcon,
    Instagram,
    Twitter,
    Facebook,
    Linkedin,
    Youtube,
    Github,
    ArrowRight,
    ArrowLeft,
    ArrowUp,
    ArrowDown,
    Plus,
    Minus,
    Edit,
    Trash2,
    Save,
    XCircle,
    CheckCircle,
    AlertCircle,
    Info,
    Loader2,
    Sparkles,
    Target,
    TrendingUp,
    Award as Trophy,
    School,
    Library,
    PenTool,
    Palette,
    Music,
    Activity,
    Zap,
    Shield,
    Lock,
    Unlock,
    Key,
    CreditCard,
    DollarSign,
    ShoppingCart,
    Package,
    Truck,
    Folder,
    File,
    Files,
    Copy,
    Printer,
    Scan,
    QrCode,
    Barcode,
    Tag,
    Tags,
    Bookmark,
    Flag,
    HelpCircle,
    AlertTriangle,
    CheckSquare,
    Square,
    Circle,
    Dot,
    List,
    Grid,
    LayoutGrid,
    LayoutList,
    Columns,
    Table,
    Filter,
    SortAsc,
    SortDesc,
    MoreHorizontal,
    MoreVertical,
    DotVertical,
    ChevronDown,
    ChevronUp,
    ChevronsLeft,
    ChevronsRight,
    ChevronsUp,
    ChevronsDown,
    PanelLeft,
    PanelRight,
    Maximize2,
    Minimize2,
    Fullscreen,
    Shrink,
    Move,
    RotateCw,
    RotateCcw,
    RefreshCw,
    Sun,
    Moon,
    Cloud,
    CloudRain,
    CloudSnow,
    CloudLightning,
    Wind,
    Thermometer,
    Droplets,
    Flame,
    Lightbulb,
    Camera,
    CameraOff,
    Mic,
    MicOff,
    Volume2,
    VolumeX,
    Headphones,
    Radio,
    Tv,
    Monitor,
    Smartphone,
    Tablet,
    Laptop,
    Computer,
    Server,
    Database,
    Wifi,
    WifiOff,
    Bluetooth,
    Usb,
    HardDrive,
    Cpu,
    MemoryStick,
    Battery,
    BatteryCharging,
    Plug,
    Power,
    ToggleLeft,
    ToggleRight,
    GitBranch,
    GitCommit,
    GitMerge,
    GitPullRequest,
    GitGraph,
    Code,
    Code2,
    Terminal,
    Command,
    Keyboard,
    Mouse,
    Touchpad,
    Gamepad2,
    Backpack,
    Briefcase,
    Cast,
    ProjectionScreen
} from 'lucide-react';

export type { LucideProps } from 'lucide-react';

/**
 * Icon Mapping - collectivités tous les icons yang dibutuhkan
 * Pakai object lookup untuk dynamic icons
 */
export const IconMap = {
    calendar: Calendar,
    mapPin: MapPin,
    mail: Mail,
    globe: Globe,
    phone: Phone,
    eye: Eye,
    clock: Clock,
    user: User,
    users: Users,
    book: Book,
    graduationCap: GraduationCap,
    award: Award,
    star: Star,
    check: Check,
    x: X,
    chevronRight: ChevronRight,
    chevronLeft: ChevronLeft,
    menu: Menu,
    search: Search,
    bell: Bell,
    settings: Settings,
    logOut: LogOut,
    home: Home,
    fileText: FileText,
    image: Image,
    video: Video,
    play: Play,
    pause: Pause,
    heart: Heart,
    share2: Share2,
    messageCircle: MessageCircle,
    thumbsUp: ThumbsUp,
    send: Send,
    download: Download,
    upload: Upload,
    externalLink: ExternalLink,
    link: LinkIcon,
    instagram: Instagram,
    twitter: Twitter,
    facebook: Facebook,
    linkedin: Linkedin,
    youtube: Youtube,
    github: Github,
    arrowRight: ArrowRight,
    arrowLeft: ArrowLeft,
    arrowUp: ArrowUp,
    arrowDown: ArrowDown,
    plus: Plus,
    minus: Minus,
    edit: Edit,
    trash2: Trash2,
    save: Save,
    xCircle: XCircle,
    checkCircle: CheckCircle,
    alertCircle: AlertCircle,
    info: Info,
    loader2: Loader2,
    sparkles: Sparkles,
    target: Target,
    trendingUp: TrendingUp,
    trophy: Trophy,
    school: School,
    library: Library,
    penTool: PenTool,
    palette: Palette,
    music: Music,
    activity: Activity,
    zap: Zap,
    shield: Shield,
    lock: Lock,
    unlock: Unlock,
    key: Key,
    creditCard: CreditCard,
    dollarSign: DollarSign,
    shoppingCart: ShoppingCart,
    package: Package,
    truck: Truck,
    folder: Folder,
    file: File,
    files: Files,
    copy: Copy,
    printer: Printer,
    scan: Scan,
    qrCode: QrCode,
    barcode: Barcode,
    tag: Tag,
    tags: Tags,
    bookmark: Bookmark,
    flag: Flag,
    helpCircle: HelpCircle,
    alertTriangle: AlertTriangle,
    checkSquare: CheckSquare,
    square: Square,
    circle: Circle,
    dot: Dot,
    list: List,
    grid: Grid,
    layoutGrid: LayoutGrid,
    layoutList: LayoutList,
    columns: Columns,
    table: Table,
    filter: Filter,
    sortAsc: SortAsc,
    sortDesc: SortDesc,
    moreHorizontal: MoreHorizontal,
    moreVertical: MoreVertical,
    dotVertical: DotVertical,
    chevronDown: ChevronDown,
    chevronUp: ChevronUp,
    chevronsLeft: ChevronsLeft,
    chevronsRight: ChevronsRight,
    chevronsUp: ChevronsUp,
    chevronsDown: ChevronsDown,
    panelLeft: PanelLeft,
    panelRight: PanelRight,
    maximize2: Maximize2,
    minimize2: Minimize2,
    fullscreen: Fullscreen,
    shrink: Shrink,
    move: Move,
    rotateCw: RotateCw,
    rotateCcw: RotateCcw,
    refreshCw: RefreshCw,
    sun: Sun,
    moon: Moon,
    cloud: Cloud,
    cloudRain: CloudRain,
    cloudSnow: CloudSnow,
    cloudLightning: CloudLightning,
    wind: Wind,
    thermometer: Thermometer,
    droplets: Droplets,
    flame: Flame,
    lightbulb: Lightbulb,
    camera: Camera,
    cameraOff: CameraOff,
    mic: Mic,
    micOff: MicOff,
    volume2: Volume2,
    volumeX: VolumeX,
    headphones: Headphones,
    radio: Radio,
    tv: Tv,
    monitor: Monitor,
    smartphone: Smartphone,
    tablet: Tablet,
    laptop: Laptop,
    computer: Computer,
    server: Server,
    database: Database,
    wifi: Wifi,
    wifiOff: WifiOff,
    bluetooth: Bluetooth,
    usb: Usb,
    hardDrive: HardDrive,
    cpu: Cpu,
    memoryStick: MemoryStick,
    battery: Battery,
    batteryCharging: BatteryCharging,
    plug: Plug,
    power: Power,
    toggleLeft: ToggleLeft,
    toggleRight: ToggleRight,
    gitBranch: GitBranch,
    gitCommit: GitCommit,
    gitMerge: GitMerge,
    gitPullRequest: GitPullRequest,
    gitGraph: GitGraph,
    code: Code,
    code2: Code2,
    terminal: Terminal,
    command: Command,
    keyboard: Keyboard,
    mouse: Mouse,
    touchpad: Touchpad,
    gamepad2: Gamepad2,
    backpack: Backpack,
    briefcase: Briefcase,
    cast: Cast,
    projectionScreen: ProjectionScreen,
};

export type IconName = keyof typeof IconMap;

/**
 * Dynamic Icon Component
 *
 * @example
 * <Icon name="calendar" className="w-5 h-5" />
 * <Icon name="user" size={24} color="#003366" />
 */
interface IconProps {
    name: IconName;
    className?: string;
    size?: number;
    color?: string;
    strokeWidth?: number;
}

export function Icon({ name, className = '', size = 24, color, strokeWidth = 2 }: IconProps) {
    const LucideIcon = IconMap[name];

    if (!LucideIcon) {
        console.warn(`Icon "${name}" not found in IconMap`);
        return null;
    }

    return (
        <LucideIcon
            className={className}
            size={size}
            color={color}
            strokeWidth={strokeWidth}
        />
    );
}

// Export semua icon individually juga
export {
    Calendar,
    MapPin,
    Mail,
    Globe,
    Phone,
    Eye,
    Clock,
    User,
    Users,
    Book,
    GraduationCap,
    Award,
    Star,
    Check,
    X,
    ChevronRight,
    ChevronLeft,
    Menu,
    Search,
    Bell,
    Settings,
    LogOut,
    Home,
    FileText,
    Image,
    Video,
    Play,
    Pause,
    Heart,
    Share2,
    MessageCircle,
    ThumbsUp,
    Send,
    Download,
    Upload,
    ExternalLink,
    LinkIcon as Link,
    Instagram,
    Twitter,
    Facebook,
    Linkedin,
    Youtube,
    Github,
    ArrowRight,
    ArrowLeft,
    ArrowUp,
    ArrowDown,
    Plus,
    Minus,
    Edit,
    Trash2,
    Save,
    XCircle,
    CheckCircle,
    AlertCircle,
    Info,
    Loader2,
    Sparkles,
    Target,
    TrendingUp,
    Trophy,
    School,
    Library,
    PenTool,
    Palette,
    Music,
    Activity,
    Zap,
    Shield,
    Lock,
    Unlock,
    Key,
    CreditCard,
    DollarSign,
    ShoppingCart,
    Package,
    Truck,
    Folder,
    File,
    Files,
    Copy,
    Printer,
    Scan,
    QrCode,
    Barcode,
    Tag,
    Tags,
    Bookmark,
    Flag,
    HelpCircle,
    AlertTriangle,
    CheckSquare,
    Square,
    Circle,
    Dot,
    List,
    Grid,
    LayoutGrid,
    LayoutList,
    Columns,
    Table,
    Filter,
    SortAsc,
    SortDesc,
    MoreHorizontal,
    MoreVertical,
    DotVertical,
    ChevronDown,
    ChevronUp,
    ChevronsLeft,
    ChevronsRight,
    ChevronsUp,
    ChevronsDown,
    PanelLeft,
    PanelRight,
    Maximize2,
    Minimize2,
    Fullscreen,
    Shrink,
    Move,
    RotateCw,
    RotateCcw,
    RefreshCw,
    Sun,
    Moon,
    Cloud,
    CloudRain,
    CloudSnow,
    CloudLightning,
    Wind,
    Thermometer,
    Droplets,
    Flame,
    Lightbulb,
    Camera,
    CameraOff,
    Mic,
    MicOff,
    Volume2,
    VolumeX,
    Headphones,
    Radio,
    Tv,
    Monitor,
    Smartphone,
    Tablet,
    Laptop,
    Computer,
    Server,
    Database,
    Wifi,
    WifiOff,
    Bluetooth,
    Usb,
    HardDrive,
    Cpu,
    MemoryStick,
    Battery,
    BatteryCharging,
    Plug,
    Power,
    ToggleLeft,
    ToggleRight,
    GitBranch,
    GitCommit,
    GitMerge,
    GitPullRequest,
    GitGraph,
    Code,
    Code2,
    Terminal,
    Command,
    Keyboard,
    Mouse,
    Touchpad,
    Gamepad2,
    Backpack,
    Briefcase,
    Cast,
    ProjectionScreen,
};